import type { Chapter } from './book';

export const chapters: Chapter[] = [
  {
    id: 1,
    ru: 'Хуки',
    en: 'Hooks',
    type: 'react',
    load: () => import('./chapters/react/hooks/HooksChapter'),
  },
  {
    id: 2,
    ru: 'Утилитарные типы',
    en: 'Utility Types',
    type: 'ts',
    load: () => import('./chapters/ts/UtilityTypesChapter'),
  },
  {
    id: 3,
    ru: 'Интерфейсы и типы',
    en: 'Interfaces and Types',
    type: 'ts',
    load: () => import('./chapters/ts/InterfacesAndTypes'),
  },
  {
    id: 4,
    ru: 'Ключи',
    en: 'Keys',
    type: 'react',
    load: () => import('./chapters/react/KeysChapter'),
  },
  {
    id: 5,
    ru: 'Паттерн «const-объект как enum»',
    en: 'Const object as enum pattern',
    type: 'ts',
    load: () => import('./chapters/ts/ConstObjectAsEnumPattern'),
  },
  {
    id: 6,
    ru: 'Правила использования хуков',
    en: 'Rules of Hooks',
    type: 'react',
    load: () => import('./chapters/react/HooksRulesChapter'),
  },
  {
    id: 7,
    ru: 'Цикл событий',
    en: 'Event loop',
    type: 'js',
    load: () => import('./chapters/js/EventLoopChapter'),
  },
  {
    id: 8,
    ru: 'Метод reduce',
    en: 'Array.reduce',
    type: 'js',
    load: () => import('./chapters/js/ReduceChapter'),
  },
  {
    id: 9,
    ru: 'Метод flatMap',
    en: 'Array.flatMap',
    type: 'js',
    load: () => import('./chapters/js/FlatMapChapter'),
  },
  {
    id: 10,
    ru: 'Специальные типы',
    en: 'Special Types',
    type: 'ts',
    load: () => import('./chapters/ts/SpecialTypesChapter'),
  },
  {
    id: 11,
    ru: 'RDT',
    en: 'React Developer Tools',
    type: 'react',
    load: () => import('./chapters/react/ReactDevToolsChapter'),
  },
  {
    id: 12,
    ru: 'Замыкания',
    en: 'Closures',
    type: 'js',
    load: () => import('./chapters/js/ClosuresChapter'),
  },
];
